FROM node:20-alpine

WORKDIR /app

# Copy package.json and install deps
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose React dev server port
EXPOSE 3000

# Use React dev server for live reload
CMD ["npm", "start"]
