version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tic-server
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: tic-client
    depends_on:
      - server
    ports:
      - "3001:80"
