version: "3.8"
services:
  server:
    container_name: tic-server-prod
    image: ttc-server-prod:latest
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
  client:
    container_name: tic-client-prod
    image: ttc-client-prod:latest
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    ports:
      - "3001:80"
