version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: tic-server
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: tic-client
    depends_on:
      - server
    ports:
      - "3001:80"
